### ISSUE TITLE
Getting System.NullReferenceException

### ISSUE THREAD

**Issue by NotAClue** [madskristensen/CssTools#14] opened 2018-08-16 09:59 UTC
### Installed product versions
- Visual Studio: 2017 Professional Preview (15.8.0 Preview 5.0)
- This extension: 1.1.21

### Description
I get this error every time I open a .Less file
System.NullReferenceException: 
Object reference not set to an instance of an object. 
at CssTools.CssExtensions.GetDeclarations(RuleBlock rule) in 
C:\projects\csstools\src\ExtensionMethods\CssExtensions.cs:line 45 at
CssTools.VendorClassifier.UpdateDeclarationCache(ParseItem item) in
C:\projects\csstools\src\Classify\VendorClassifier.cs:line 116 at
CssTools.VendorClassifier..ctor(IClassificationTypeRegistryService registry, ITextBuffer buffer) in
C:\projects\csstools\src\Classify\VendorClassifier.cs:line 59 at
CssTools.VendorClassifierProvider.<>c__DisplayClass4_0.<GetClassifier>b__0() in
C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37 at
Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator) at
CssTools.VendorClassifierProvider.GetClassifier(ITextBuffer textBuffer) in
C:\projects\csstools\src\Classify\VendorClassifier.cs:line 37 at
Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.<>c__DisplayClass12_0`1.<CreateTagger>b__0(IClassifierProvider provider) at
Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource) --- End of stack trace from previous location where exception was thrown --- at
Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

### Steps to recreate
1. have this extension installed 
2. open Visual Studio
3. open a .Less file 
4. move cursor into editor
5. get error popup then open see "ActivityLog.xml"

### Current behavior
just get the error at first opening of .Less file

### Expected behavior
not get the error?

**Comment by Saibamen** [comment] 2018-08-16 12:34
This same error on stable VS 15.8.0, Win 10

**Comment by conficient** [comment] 2018-08-16 13:37
Duplicate of #11

**Comment by madskristensen** [comment] 2018-08-16 15:38
Fixed in latest release

**Closed by madskristensen** 2018-08-16 15:38 UTC
